### ISSUE TITLE
Few issues with current setup

### ISSUE THREAD

**Issue by bloodmc** [zml2008/configurate#13]
1. Nodes are unable to retrieve parent. Adding a getParent() method would be useful.

1. There is no way to create a SimpleCommentedConfigurationNode with a path, value, and comment in 1 line. Currently I have to create the node then call setComment on it.

1. I do not see a way to retrieve the current path of a node. So if I do something like this

    ```
    ConfigurationNode node = this.config.getNode("general").getChild("config-enabled").setValue(true);
    ```
    I should be able to use node.getPath()  which would return general.config-enabled

1. Is it possible to pass a path and have nodes generated, if they do not exist, for the full path? so if I use the same example above but instead wrote it as

    ```
    ConfigurationNode node = this.config.getNode("general.config-enabled").setValue(true);
    ```

    The output would be

    ```
    general {
      config-enabled=true
    }
    ```

1. Perhaps a getKey() method? which would return the name of the current node. Using the same example as above

    node.getKey() would return "config-enabled"
    node.getPath() would return "general.config-enabled"
    node.getValue() would return "true"

1. Retrieving a child node that contains a value which is not a map or list always creates a new node object

   ```
   rootNode.getNode(key).getChild(childKey)
   ```

   Example above if called twice will return 2 different objects.

**Comment by zml2008** [comment]
1. This exists internally -- only issue is that this is not constant until the node is created
2. node.getNode("general", "config-enabled").setValue(true).setComment("Aren't configs great?");
3. Nodes currently don't hold their full paths. Might be able to build this up from parent links though.
4. works as this.config.getNode("general", "config-enabled").setValue(true);
5. Same as 1, but it's probably good to have this (not consistent only on list element nodes because index may change)
6. If the node has a value set, those should return the same value -- tested at https://github.com/zml2008/configurate/blob/master/configurate-core/src/test/java/ninja/leaping/configurate/SimpleConfigurationNodeTest.java#L55

**Comment by bloodmc** [comment]
1. OK can we make this public as it is useful.
2. OK please have setComment return the node as it currently is void.
3. Sounds good.
4. OK perfect
5. OK
6. Yup, that was it. Thanks!

**Comment by bloodmc** [comment]
@zml2008 1 more thing, can setComment return the node? Thanks!

**Comment by bloodmc** [comment]
Nevermind, I didn't realise it was done in previous commit. Thanks again.
