### ISSUE TITLE
ConfigurationOption acceptsType losing information somewhere

### ISSUE THREAD

**Issue by me4502** [zml2008/configurate#51]
For context, I am adding an accepted type, which is BlockState.

To verify this has been added, I call..
```
        if(!configurationOptions.acceptsType(BlockTypes.AIR.getDefaultState().getClass()))
            throw new RuntimeException();
```

This runs fine with no error.

After calling this however,
```      
config = configManager.load(CraftBookPlugin.<CraftBookPlugin>inst().configurationOptions);

if(!config.getNode("anything").getOptions().acceptsType(BlockTypes.AIR.getDefaultState().getClass()))
            throw new RuntimeException();
```

This will now throw the exception.

**Comment by zml2008** [comment]
Ok, so looked into this. Configuration loaders set the types they accept because the accepted types are controlled by the loader. Hocon only has a certain set of supported types, which you cannot change.

If you're registering a TypeSerializer, you have to use the TypeToken-parametered method to setValue -- changing acceptedTypes doesn't affect how serialization works at the Configurate level.
