### ISSUE TITLE
Change GSON options to serialize long as a string

### ISSUE THREAD

**Issue by dumptruckman** [zml2008/configurate#52]
When serializing long, by default GSON will store it in scientific notation which makes it a little tricky to deserialize.

**Comment by zml2008** [comment]
It looks like this is an issue with how GSON handles numbers -- it makes no distinction between integer and floating-point numbers and provides no ability to 'peek' at future values.

Currently, your best bet is probably to use the jackson-based implementation of configurate (`configurate-json`) -- it still gets this wrong in the current release, but I've been able to fix it to work properly in the future, starting with commit a682bbe.

If you really need gson for some reason you'll have to bring this issue up with a) the gson devs and b) mojang, since we're stuck to the version of gson that minecraft uses.
